### ISSUE TITLE
Background service for sensing

### ISSUE THREAD

**Issue by rouvoy** [Apolline-Lille/apolline-android#13]
It appears that the app stops gathering particle measurements when the app in not on focus (e.g., screen off), while it should use a service that keeps collecting the measurements from the sensor device, even if they are not displayed.

**Comment by kaal-dam** [comment]
we already use a service ... and the service isn't stopped when app is not in focus, so it should continue collecting measurement, but it may be possible that the lifecycle observer only notify the view if the view is on focus ( which can cause some gap on the graph), i'll check the db entry tomorrow to confirm it (or not)
