### ISSUE TITLE
Export db to file

### ISSUE THREAD

**Issue by kaal-dam** [Apolline-Lille/apolline-android#14]
add an option to export the db into a file

which type of file ? 
- CSV
- pure text
- json
- othe ?

**Comment by rouvoy** [comment]
It would be good to have a menu item to export the db in json or csv and share it via an email or filesharing solution (eg. Dropbox)

**Comment by kaal-dam** [comment]
the menu item was already planned, i just need to know the format of the file that will be the best for the students who need it

for the share by email/filesharing solution i think it will be on a second time since it's less critical than file export.

**Comment by kaal-dam** [comment]
sample (test is the row version, data is the readable version)
[file.zip](https://github.com/Apolline-Lille/apolline-android/files/1543012/file.zip)

**Comment by rouvoy** [comment]
Please also consider CSV export for LOA.

**Comment by Sparow199** [comment]
I'm working in this issues, i tried [Json2Flat](https://github.com/opendevl/Json2Flat) but it doesn't compile with current project configuration. So i should write a lot of codes in order to do it. In addition, it will run only with LOA device. I think it will be better to take JSON file and convert it to CSV, it takes few seconds !

**Comment by rouvoy** [comment]
I basically agree, but your end-users are used to process CSV files.

Did you look at these solutions : https://github.com/search?l=Java&q=json2csv&type=Repositories&utf8=✓

**Comment by kaal-dam** [comment]
I don't think since @Sparow199 have write is own method apparently, maybe interesting to reduce boilerplate but i think we can replace actual tag by a simple enhancement one for this
