### ISSUE TITLE
Add async tasks to manage Room ORM

### ISSUE THREAD

**Issue by Sparow199** [Apolline-Lille/apolline-android#15]

**Comment by rouvoy** [comment]
What is the "Room" database?

**Comment by kaal-dam** [comment]
@Sparow199 confused orm and database, room is the name of the orm we use

**Comment by kaal-dam** [comment]
Hum, looking at the referenced commit i don't see anything looking like asynchronous call

**Comment by kaal-dam** [comment]
issue should have been closed in commit 4e128a511d35fe5f281f63a29dfdd27520197f55
