### ISSUE TITLE
Use geohash instead of raw location

### ISSUE THREAD

**Issue by rouvoy** [Apolline-Lille/apolline-android#21]
Instead of reporting on raw `lon` and `lat` coordinates, encode them as a `geohash` (cf. https://en.wikipedia.org/wiki/Geohash).

Some client libraries are available for encoding it:
https://github.com/search?utf8=✓&q=geohash+language%3AKotlin&type=Repositories&ref=advsearch&l=Kotlin&l=

**Comment by kaal-dam** [comment]
2 potential library : 
github : https://github.com/astrapi69/jgeohash
mvn repo : https://mvnrepository.com/artifact/de.alpharogroup/jgeohash-core/2.4.0

github : https://github.com/davidmoten/geo
mvn repo : https://mvnrepository.com/artifact/com.github.davidmoten/geo/0.7.6

**Comment by rouvoy** [comment]
https://github.com/astrapi69/jgeohash looks promising, in particular the potential support for indoor geoloc (based on IP address or cells).

**Comment by kaal-dam** [comment]
pour utiliser les ip il semble qu'il faille faut ajouter :
implementation 'de.alpharogroup:jgeohash-geoip:2.4.0' 
en plus de 
implementation 'de.alpharogroup:jgeohash-core:2.4.0'
qui ne représente que le core applicatif

**Comment by Sparow199** [comment]
closed 60517c68d094ed44f6f52881306c5173513c1938
