### ISSUE TITLE
Add instructions for pairing the sensor device

### ISSUE THREAD

**Issue by rouvoy** [Apolline-Lille/apolline-android#27]
The first pairing of the sensor device is not documented and one may fail to find the code to pair the device.

This also include instructions for initiating the pairing phase.

**Comment by kaal-dam** [comment]
> one may fail to find the code
technically nobody can find the code since it's managed by the ioio library for the only sensor actualy supported by the app, so document it will be hard.

**Comment by rouvoy** [comment]
The code for the IOIO sensor is `4545`, but one cannot guess it, in particular if it is used by citizens and not experts.

We should therefore include a GettingStarted screen to help the user to pair her sensor device with the smartphone.
