### ISSUE TITLE
App keeps crashing upon launch

### ISSUE THREAD

**Issue by rouvoy** [Apolline-Lille/apolline-android#28]
After working correctly for several hours, the app now keeps crashing upon launch on an LG4 smartphone.

**Comment by rouvoy** [comment]
It seems to come back to normal behaviour after rebooting the smartphone.

**Comment by rouvoy** [comment]
The issue seems to be related to a memory problem... it is likely that the main plot contains to many measurements after several hours of active monitoring. Maybe one can only keep a buffer of last `x` hours and consider a coarser granularity of reporting than the actual one.

**Comment by kaal-dam** [comment]
possible fix in commit 695deea5906dfd0c8b951449ccd120fc358bd5ce

the dataset used to display the graph have not limit of how many point he should keep in memory, only the limit of point he should effectively display on screen

need more test before closing the issue to find if other thing can explain such memory problem
