### ISSUE TITLE
Display the charge of the sensor

### ISSUE THREAD

**Issue by rouvoy** [Apolline-Lille/apolline-android#30]
If the information is reported by the sensor device, it could be interesting to display the current battery level of the sensor device in order to inform the user when it requires to be charged.

**Comment by Sparow199** [comment]
The current sensors don't send any information about battery level !

**Comment by rouvoy** [comment]
Unfortunately not, so let's close the issue for the time being, focusing on the status of the connection as an indication of the status of the sensor.
