### ISSUE TITLE
Ne jamais commit sur Master

### ISSUE THREAD

**Issue by Sparow199** [Apolline-Lille/apolline-android#5]
Le pull de master vers develop crée des conflits:
Les noms des classes ont changés et le fameux bug de R arrive et il nous fait perdre trop de temps.

**Comment by rouvoy** [comment]
1. Vous pouvez utiliser un `git rebase` pour aligner la branche `develop` (ou toute autre branche) avec la branche `master`
2. Vous pouvez utiliser le fichier `.gitignore` pour exclure le fichier `R.java` des fichiers qui doivent être historiés dans le Git.
