### ISSUE TITLE
v1.0.1, 1.0.2, 1.0.3 are missing the app binary (apk)

### ISSUE THREAD

**Issue by rouvoy** [Apolline-Lille/apolline-android#9]
Please, don't forget to include it as part of the release and to document the changelog.

**Comment by kaal-dam** [comment]
apk isn't still part of the automatic release, i needed to put it manually @Sparow199

**Comment by Sparow199** [comment]
You haven't the right Travis config file on Master branch. Just merge Develop to Master to fix apk autodeploy.

**Comment by kaal-dam** [comment]
no commit reference this issue as fixed
